In [55]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import glob,os
from geopy.distance import geodesic

In [56]:
exist=gpd.read_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/existing_bus_center.shp')

In [57]:
df=gpd.read_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/taz_max5.shp')

In [58]:
exist['lon1']=exist.centroid.x 
exist['lat1']=exist.centroid.y

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\4003808661.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  exist['lon1']=exist.centroid.x
C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\4003808661.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  exist['lat1']=exist.centroid.y

In [59]:
exist['lon1']

0   -82.387449
1   -82.322391
2   -82.297501
Name: lon1, dtype: float64

In [60]:
exist['lat1']

0    29.625051
1    29.649631
2    29.647004
Name: lat1, dtype: float64

In [61]:
df['lon'] = df.centroid.x  
df['lat'] = df.centroid.y

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\579834366.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  df['lon'] = df.centroid.x
C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\579834366.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  df['lat'] = df.centroid.y

In [62]:
df

,index,TAZ,score,ORIG_FID,geometry,lon,lat
0,473,101,40.882309,0,POINT (-82.32886 29.63622),-82.328859,29.636217
1,476,102,42.770541,1,POINT (-82.33818 29.63647),-82.338178,29.636472
2,99,103,38.122964,2,POINT (-82.33920 29.63604),-82.339199,29.636040
3,445,104,29.980444,3,POINT (-82.33936 29.62827),-82.339361,29.628271
4,617,106,34.961539,4,POINT (-82.35116 29.63398),-82.351164,29.633979
...,...,...,...,...,...,...,...
168,253,94,40.478481,168,POINT (-82.30585 29.65064),-82.305845,29.650641
169,49,95,43.845789,169,POINT (-82.30949 29.64584),-82.309492,29.645840
170,262,96,27.509972,170,POINT (-82.30585 29.63374),-82.305852,29.633743
171,8,97,38.899434,171,POINT (-82.30152 29.64892),-82.301519,29.648925
172,369,99,40.758158,172,POINT (-82.33932 29.63999),-82.339319,29.639995

In [63]:

# Calculate the distance between (lon1, lat1) and (lon2, lat2) using the Haversine formula
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.625051, -82.387449)
    return geodesic(point_a, point_b).miles

df['Distance'] = df.apply(calculate_distance, axis=1)

In [64]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.649631, -82.322391)
    return geodesic(point_a, point_b).miles

df['Distance2'] = df.apply(calculate_distance, axis=1)

In [65]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.647004, -82.297501)
    return geodesic(point_a, point_b).miles

df['Distance3'] = df.apply(calculate_distance, axis=1)

In [66]:
df=df[df['Distance']>1.5]
df=df[df['Distance2']>1.5]
df=df[df['Distance3']>1.5]

df

,index,TAZ,score,ORIG_FID,geometry,lon,lat,Distance,Distance2,Distance3
3,445,104,29.980444,3,POINT (-82.33936 29.62827),-82.339361,29.628271,2.902254,1.790849,2.830009
4,617,106,34.961539,4,POINT (-82.35116 29.63398),-82.351164,29.633979,2.268380,2.039461,3.351165
5,235,107,51.152942,5,POINT (-82.35058 29.63657),-82.350581,29.636571,2.356119,1.919897,3.273577
7,618,109,43.505469,7,POINT (-82.34536 29.63511),-82.345361,29.635112,2.625713,1.705912,2.993902
10,389,113,42.708938,10,POINT (-82.35141 29.63884),-82.351412,29.638842,2.367400,1.897644,3.292035
...,...,...,...,...,...,...,...,...,...,...
144,469,65,34.999980,144,POINT (-82.30611 29.68833),-82.306108,29.688327,6.552850,2.839527,2.892885
145,455,66,32.550051,145,POINT (-82.30580 29.68169),-82.305798,29.681691,6.272925,2.423343,2.440736
146,456,67,33.210052,146,POINT (-82.30580 29.67680),-82.305804,29.676799,6.068893,2.120673,2.112112
157,131,79,34.356300,157,POINT (-82.29910 29.67019),-82.299104,29.670191,6.157770,1.991930,1.599928
158,132,80,22.823525,158,POINT (-82.27632 29.68608),-82.276320,29.686084,7.897293,3.739510,2.978033

In [67]:
df.columns

Index(['index', 'TAZ', 'score', 'ORIG_FID', 'geometry', 'lon', 'lat',
       'Distance', 'Distance2', 'Distance3'],
      dtype='object')

In [68]:
df2=df[['index', 'TAZ', 'score',
       'Distance', 'Distance2', 'Distance3']]
#should select from these centroids, merge with the buffer zone based on the index
gdf = gpd.read_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/new_score_recent4.shp')[['index','geometry']]
result2=pd.merge(gdf,df2,how='right',on='index')

In [69]:
result2.to_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/updated5/select_buffer.shp')

In [70]:
#should select from these centroids, merge with the buffer zone based on the index
df.to_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/updated5/centroid_select.shp')

In [72]:
gdf

   score                     geometry
0    0.7   POINT (-74.00600 40.71280)
1    0.9  POINT (-118.24370 34.05220)
2    0.6   POINT (-87.62980 41.87810)
3    1.2   POINT (-75.16520 39.95260)
4    0.8  POINT (-122.41940 37.77490)
5    1.5   POINT (-97.74310 30.26720)
6    2.0   POINT (-96.79700 32.77670)

In [73]:
point_a = (row['lat'], row['lon'])
point_b = (29.647004, -82.297501)
geodesic(point_a, point_b).miles

,index,TAZ,score,ORIG_FID,geometry,lon,lat,Distance,Distance2,Distance3
3,445,104,29.980444,3,POINT (-82.33936 29.62827),-82.339361,29.628271,2.902254,1.790849,2.830009
4,617,106,34.961539,4,POINT (-82.35116 29.63398),-82.351164,29.633979,2.268380,2.039461,3.351165
5,235,107,51.152942,5,POINT (-82.35058 29.63657),-82.350581,29.636571,2.356119,1.919897,3.273577
7,618,109,43.505469,7,POINT (-82.34536 29.63511),-82.345361,29.635112,2.625713,1.705912,2.993902
10,389,113,42.708938,10,POINT (-82.35141 29.63884),-82.351412,29.638842,2.367400,1.897644,3.292035
...,...,...,...,...,...,...,...,...,...,...
144,469,65,34.999980,144,POINT (-82.30611 29.68833),-82.306108,29.688327,6.552850,2.839527,2.892885
145,455,66,32.550051,145,POINT (-82.30580 29.68169),-82.305798,29.681691,6.272925,2.423343,2.440736
146,456,67,33.210052,146,POINT (-82.30580 29.67680),-82.305804,29.676799,6.068893,2.120673,2.112112
157,131,79,34.356300,157,POINT (-82.29910 29.67019),-82.299104,29.670191,6.157770,1.991930,1.599928
158,132,80,22.823525,158,POINT (-82.27632 29.68608),-82.276320,29.686084,7.897293,3.739510,2.978033

In [79]:
#test6
test6=gpd.read_file('C:/Users/anranzheng/Dropbox (UFL)/Mobility Hub/Anran/module builder/results/updated5/test6_center.shp')

In [80]:
test6['lon'] = test6.centroid.x  
test6['lat'] = test6.centroid.y

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\3092614544.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  test6['lon'] = test6.centroid.x
C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\3092614544.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  test6['lat'] = test6.centroid.y

In [81]:
test6

,index,TAZ,score,Distance,Distance2,Distance3,ORIG_FID,geometry,lon,lat
0,392,114,57.444967,2.906679,1.505311,3.003326,0,POINT (-82.34739 29.64863),-82.347385,29.648629
1,524,155,46.175827,7.500943,3.309432,2.517415,1,POINT (-82.27992 29.68017),-82.279918,29.680171
2,270,169,41.848820,4.922482,2.253629,1.907617,2,POINT (-82.30583 29.62028),-82.305834,29.620282
3,302,390,50.271357,2.510752,5.222751,6.730557,3,POINT (-82.40886 29.65634),-82.408863,29.656338
4,326,398,47.447617,6.120879,4.592347,5.558059,4,POINT (-82.35590 29.70954),-82.355904,29.709540
5,529,61,46.236599,5.746762,1.631047,1.554367,5,POINT (-82.30582 29.66837),-82.305816,29.668371

In [96]:
df2=df[['index','score','lat','lon']]

In [97]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.648629, -82.347385)
    return geodesic(point_a, point_b).miles

df2['Distance2'] = df2.apply(calculate_distance, axis=1)

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\3171495104.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Distance2'] = df2.apply(calculate_distance, axis=1)

In [98]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.680171, -82.279918)
    return geodesic(point_a, point_b).miles

df2['Distance3'] = df2.apply(calculate_distance, axis=1)

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\585568999.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Distance3'] = df2.apply(calculate_distance, axis=1)

In [99]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.620282, -82.305834)
    return geodesic(point_a, point_b).miles

df2['Distance4'] = df2.apply(calculate_distance, axis=1)

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\68359964.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Distance4'] = df2.apply(calculate_distance, axis=1)

In [100]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.656338, -82.408863)
    return geodesic(point_a, point_b).miles

df2['Distance5'] = df2.apply(calculate_distance, axis=1)

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\1696708978.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Distance5'] = df2.apply(calculate_distance, axis=1)

In [101]:
test6

,index,TAZ,score,Distance,Distance2,Distance3,ORIG_FID,geometry,lon,lat
0,392,114,57.444967,2.906679,1.505311,3.003326,0,POINT (-82.34739 29.64863),-82.347385,29.648629
1,524,155,46.175827,7.500943,3.309432,2.517415,1,POINT (-82.27992 29.68017),-82.279918,29.680171
2,270,169,41.848820,4.922482,2.253629,1.907617,2,POINT (-82.30583 29.62028),-82.305834,29.620282
3,302,390,50.271357,2.510752,5.222751,6.730557,3,POINT (-82.40886 29.65634),-82.408863,29.656338
4,326,398,47.447617,6.120879,4.592347,5.558059,4,POINT (-82.35590 29.70954),-82.355904,29.709540
5,529,61,46.236599,5.746762,1.631047,1.554367,5,POINT (-82.30582 29.66837),-82.305816,29.668371

In [102]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.709540, -82.355904)
    return geodesic(point_a, point_b).miles

df2['Distance'] = df2.apply(calculate_distance, axis=1)

C:\Users\anranzheng\AppData\Local\Temp\ipykernel_5924\4112385154.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Distance'] = df2.apply(calculate_distance, axis=1)

In [103]:
def calculate_distance(row):
    point_a = (row['lat'], row['lon'])
    point_b = (29.668371, -82.305816)
    return geodesic(point_a, point_b).miles

df2['Distance6'] = df2.apply(calculate_distance, axis=1)

In [104]:
df2

,index,score,lat,lon,Distance2,Distance3,Distance4,Distance5,Distance,Distance6
3,445,29.980444,29.628271,-82.339361,1.482994,5.056429,2.091303,4.606976,5.685344,3.420781
4,617,34.961539,29.633979,-82.351164,1.034375,5.337890,2.886339,3.797772,5.212252,3.613139
5,235,51.152942,29.636571,-82.350581,0.852481,5.204700,2.917097,3.761560,5.036068,3.471366
7,618,43.505469,29.635112,-82.345361,0.938913,5.013138,2.588668,4.090767,5.165435,3.302701
10,389,42.708938,29.638842,-82.351412,0.716314,5.157606,3.025959,3.660549,4.876958,3.414848
...,...,...,...,...,...,...,...,...,...,...
144,469,34.999980,29.688327,-82.306108,3.693385,1.672280,4.686737,6.561688,3.331912,1.374603
145,455,32.550051,29.681691,-82.305798,3.382914,1.560034,4.229690,6.440816,3.571920,0.917474
146,456,33.210052,29.676799,-82.305804,3.165656,1.574157,3.892730,6.357513,3.763373,0.580513
157,131,34.356300,29.670191,-82.299104,3.262129,1.343220,3.461310,6.671167,4.360526,0.422754
158,132,22.823525,29.686084,-82.276320,4.992866,0.461191,4.867643,8.231550,5.051069,2.153091

In [105]:
df2=df2[df2['Distance']>1.5]
df2=df2[df2['Distance2']>1.5]
df2=df2[df2['Distance3']>1.5]
df2=df2[df2['Distance4']>1.5]
df2=df2[df2['Distance5']>1.5]
df2=df2[df2['Distance6']>1.5]

df2

,index,score,lat,lon,Distance2,Distance3,Distance4,Distance5,Distance,Distance6
17,565,27.591122,29.660520,-82.372408,1.713754,5.725645,4.870967,2.211895,3.519260,4.042142
25,291,29.784860,29.650508,-82.374181,1.617352,6.027170,4.609507,2.124764,4.211943,4.292785
26,588,28.656422,29.651885,-82.376245,1.750702,6.113143,4.763167,1.986165,4.155271,4.386297
28,147,28.764671,29.647992,-82.372525,1.513152,5.995468,4.443683,2.260491,4.355558,4.251487
34,53,29.922972,29.672720,-82.339249,1.729998,3.605324,4.133609,4.336933,2.726676,2.033222
35,355,24.199023,29.685775,-82.347438,2.558533,4.079205,5.158852,4.214503,1.714186,2.775662
36,359,26.038303,29.681499,-82.351538,2.277711,4.308521,5.033764,3.859207,1.949172,2.894916
37,362,32.103461,29.674063,-82.341774,1.784068,3.744147,4.289217,4.216308,2.587072,2.198131
39,448,29.403996,29.688485,-82.327840,2.986305,2.938461,4.880561,5.352932,2.225148,1.916737
43,417,27.285935,29.650945,-82.272427,4.512516,2.062840,2.915639,8.216498,6.441733,2.339881
44,345,23.895064,29.642218,-82.272029,4.555287,2.656813,2.533892,8.289640,6.852149,2.715935
49,441,23.685565,29.613253,-82.341026,2.466435,5.895830,2.172578,5.046602,6.692068,4.347456
57,79,24.020615,29.673622,-82.387664,2.972291,6.496306,6.142988,1.744497,3.125478,4.936489
59,581,24.891858,29.672291,-82.388986,2.986471,6.582574,6.153110,1.623887,3.246622,5.010032
64,414,22.660565,29.674143,-82.425116,4.995311,8.743054,8.078699,1.568377,4.823739,7.186931
65,83,17.557626,29.674224,-82.428413,5.183340,8.940909,8.257923,1.703115,4.993156,7.385276
66,81,15.049673,29.679628,-82.431876,5.512776,9.139614,8.614585,2.118852,5.011726,7.621879
67,577,26.038952,29.688657,-82.397404,4.080893,7.090026,7.247546,2.330344,2.880362,5.683087
68,403,24.396550,29.667871,-82.375280,2.138318,5.798115,5.310543,2.170788,3.097603,4.178537
69,174,25.347378,29.685112,-82.388816,3.539137,6.558358,6.697921,2.319894,2.597684,5.123651
70,558,18.688567,29.686915,-82.372337,3.034228,5.577712,6.088514,3.043445,1.845251,4.199909
71,356,24.005347,29.685742,-82.349525,2.559475,4.203974,5.218943,4.103757,1.683425,2.888440
72,161,28.476203,29.702961,-82.386666,4.425648,6.608776,7.488226,3.477696,1.904419,5.414769
81,598,20.155474,29.601907,-82.415576,5.214903,9.781703,6.725117,3.770712,8.236855,8.035881
83,201,22.224861,29.600641,-82.421481,5.550435,10.127054,7.090659,3.910677,8.474898,8.378666
84,604,19.968290,29.626098,-82.422515,4.779568,9.352380,7.033158,2.238974,7.006107,7.600945
85,608,22.473530,29.634849,-82.414288,4.135811,8.665336,6.603047,1.515683,6.228872,6.922326
91,625,11.653750,29.674391,-82.441369,5.925605,9.718897,8.965684,2.317213,5.681317,8.164069
92,603,18.639536,29.615225,-82.422559,5.074978,9.677762,7.033378,2.949207,7.633946,7.920753
104,375,40.101547,29.613516,-82.362163,2.576744,6.749970,3.421897,4.073746,6.624527,5.076316
110,164,26.392390,29.686504,-82.389063,3.618109,6.578819,6.773169,2.394876,2.548246,5.160463
111,354,25.101715,29.688526,-82.347918,2.748207,4.129968,5.338937,4.284128,1.524954,2.887824
112,361,27.764265,29.676471,-82.347970,1.917997,4.100996,4.626493,3.916616,2.327140,2.596205
118,84,24.538383,29.666661,-82.368910,1.794247,5.433079,4.960556,2.506378,3.055224,3.797105
121,200,16.887082,29.609472,-82.422687,5.273240,9.874124,7.072000,3.333443,7.977806,8.118373
123,220,21.414971,29.607196,-82.438799,6.197114,10.800215,8.053032,3.834225,8.634721,9.043213
124,576,23.871276,29.688712,-82.400156,4.206902,7.255291,7.376584,2.290528,3.023077,5.844573
133,311,31.974558,29.673930,-82.331924,1.975290,3.157432,4.014683,4.784145,2.845269,1.616433
136,115,31.745667,29.676370,-82.330830,2.154686,3.073326,4.145564,4.892538,2.737402,1.602282
137,112,29.726888,29.685223,-82.330834,2.710000,3.081998,4.719053,5.097743,2.253431,1.900437
138,111,29.752061,29.687605,-82.330845,2.862985,3.105402,4.875021,5.163342,2.133856,2.005317
139,450,29.556786,29.688431,-82.322419,3.125833,2.618656,4.798762,5.649958,2.483647,1.704761

In [106]:
df2.sort_values(by='score')

,index,score,lat,lon,Distance2,Distance3,Distance4,Distance5,Distance,Distance6
91,625,11.653750,29.674391,-82.441369,5.925605,9.718897,8.965684,2.317213,5.681317,8.164069
66,81,15.049673,29.679628,-82.431876,5.512776,9.139614,8.614585,2.118852,5.011726,7.621879
121,200,16.887082,29.609472,-82.422687,5.273240,9.874124,7.072000,3.333443,7.977806,8.118373
65,83,17.557626,29.674224,-82.428413,5.183340,8.940909,8.257923,1.703115,4.993156,7.385276
92,603,18.639536,29.615225,-82.422559,5.074978,9.677762,7.033378,2.949207,7.633946,7.920753
70,558,18.688567,29.686915,-82.372337,3.034228,5.577712,6.088514,3.043445,1.845251,4.199909
84,604,19.968290,29.626098,-82.422515,4.779568,9.352380,7.033158,2.238974,7.006107,7.600945
81,598,20.155474,29.601907,-82.415576,5.214903,9.781703,6.725117,3.770712,8.236855,8.035881
123,220,21.414971,29.607196,-82.438799,6.197114,10.800215,8.053032,3.834225,8.634721,9.043213
83,201,22.224861,29.600641,-82.421481,5.550435,10.127054,7.090659,3.910677,8.474898,8.378666
85,608,22.473530,29.634849,-82.414288,4.135811,8.665336,6.603047,1.515683,6.228872,6.922326
64,414,22.660565,29.674143,-82.425116,4.995311,8.743054,8.078699,1.568377,4.823739,7.186931
49,441,23.685565,29.613253,-82.341026,2.466435,5.895830,2.172578,5.046602,6.692068,4.347456
124,576,23.871276,29.688712,-82.400156,4.206902,7.255291,7.376584,2.290528,3.023077,5.844573
44,345,23.895064,29.642218,-82.272029,4.555287,2.656813,2.533892,8.289640,6.852149,2.715935
71,356,24.005347,29.685742,-82.349525,2.559475,4.203974,5.218943,4.103757,1.683425,2.888440
57,79,24.020615,29.673622,-82.387664,2.972291,6.496306,6.142988,1.744497,3.125478,4.936489
35,355,24.199023,29.685775,-82.347438,2.558533,4.079205,5.158852,4.214503,1.714186,2.775662
68,403,24.396550,29.667871,-82.375280,2.138318,5.798115,5.310543,2.170788,3.097603,4.178537
118,84,24.538383,29.666661,-82.368910,1.794247,5.433079,4.960556,2.506378,3.055224,3.797105
59,581,24.891858,29.672291,-82.388986,2.986471,6.582574,6.153110,1.623887,3.246622,5.010032
111,354,25.101715,29.688526,-82.347918,2.748207,4.129968,5.338937,4.284128,1.524954,2.887824
69,174,25.347378,29.685112,-82.388816,3.539137,6.558358,6.697921,2.319894,2.597684,5.123651
36,359,26.038303,29.681499,-82.351538,2.277711,4.308521,5.033764,3.859207,1.949172,2.894916
67,577,26.038952,29.688657,-82.397404,4.080893,7.090026,7.247546,2.330344,2.880362,5.683087
110,164,26.392390,29.686504,-82.389063,3.618109,6.578819,6.773169,2.394876,2.548246,5.160463
43,417,27.285935,29.650945,-82.272427,4.512516,2.062840,2.915639,8.216498,6.441733,2.339881
17,565,27.591122,29.660520,-82.372408,1.713754,5.725645,4.870967,2.211895,3.519260,4.042142
112,361,27.764265,29.676471,-82.347970,1.917997,4.100996,4.626493,3.916616,2.327140,2.596205
72,161,28.476203,29.702961,-82.386666,4.425648,6.608776,7.488226,3.477696,1.904419,5.414769
26,588,28.656422,29.651885,-82.376245,1.750702,6.113143,4.763167,1.986165,4.155271,4.386297
28,147,28.764671,29.647992,-82.372525,1.513152,5.995468,4.443683,2.260491,4.355558,4.251487
39,448,29.403996,29.688485,-82.327840,2.986305,2.938461,4.880561,5.352932,2.225148,1.916737
139,450,29.556786,29.688431,-82.322419,3.125833,2.618656,4.798762,5.649958,2.483647,1.704761
137,112,29.726888,29.685223,-82.330834,2.710000,3.081998,4.719053,5.097743,2.253431,1.900437
138,111,29.752061,29.687605,-82.330845,2.862985,3.105402,4.875021,5.163342,2.133856,2.005317
25,291,29.784860,29.650508,-82.374181,1.617352,6.027170,4.609507,2.124764,4.211943,4.292785
34,53,29.922972,29.672720,-82.339249,1.729998,3.605324,4.133609,4.336933,2.726676,2.033222
136,115,31.745667,29.676370,-82.330830,2.154686,3.073326,4.145564,4.892538,2.737402,1.602282
133,311,31.974558,29.673930,-82.331924,1.975290,3.157432,4.014683,4.784145,2.845269,1.616433
37,362,32.103461,29.674063,-82.341774,1.784068,3.744147,4.289217,4.216308,2.587072,2.198131
104,375,40.101547,29.613516,-82.362163,2.576744,6.749970,3.421897,4.073746,6.624527,5.076316

In [74]:
from itertools import combinations

# Calculate the distance between two points using the geodesic function
def calculate_distance(point1, point2):
    return geodesic(point1, point2).miles

# Select 6 points with a minimum distance of 1.5 miles between each pair
selected_points = []
for combo in combinations(df.geometry, 6):
    distances = [calculate_distance(combo[i], combo[j]) for i in range(5) for j in range(i + 1, 6)]
    if all(distance > 1.5 for distance in distances):
        selected_points = list(combo)
        break

print(selected_points)

TypeError: Failed to create Point instance from <POINT (-82.339 29.628)>.

In [78]:
df['geometry']

3      POINT (-82.33936 29.62827)
4      POINT (-82.35116 29.63398)
5      POINT (-82.35058 29.63657)
7      POINT (-82.34536 29.63511)
10     POINT (-82.35141 29.63884)
                  ...
144    POINT (-82.30611 29.68833)
145    POINT (-82.30580 29.68169)
146    POINT (-82.30580 29.67680)
157    POINT (-82.29910 29.67019)
158    POINT (-82.27632 29.68608)
Name: geometry, Length: 92, dtype: geometry

In [77]:
from scipy.spatial.distance import cdist
import random

# Function to check if a new point satisfies the distance constraint
def satisfies_distance_constraint(new_point, selected_points, min_distance):
    distances = cdist([new_point], selected_points)[0]
    return all(distance > min_distance for distance in distances)

# Select 6 points with distances greater than 1.5 miles
min_distance = 1.5  # Minimum distance in miles
selected_points = []
num_points_to_select = 6

while len(selected_points) < num_points_to_select:
    new_point = random.choice(df['geometry'])
    if satisfies_distance_constraint(new_point, selected_points, min_distance):
        selected_points.append(new_point)

# Create a new GeoDataFrame with the selected points
selected_data = {'geometry': selected_points}
selected_gdf = gpd.GeoDataFrame(selected_data, crs="EPSG:4326")

print(selected_gdf)

ValueError: The truth value of a GeoSeries is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().